# Tensorflow2.0 小练习

In [2]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [ ]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    exp_x = np.exp(x - np.max(x, dims=-1, keepdims=True)) # 解决上溢问题
    y = np.sum(exp_x, axis=-1, keepdims=True)
    prob_x = exp_x / y
    return prob_x

test_data = np.random.normal(size=[10, 5])
# (softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001
(softmax(test_data) - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [ ]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    negexp_x = np.exp(-x)
    prob_x = np.ones(shape=[10, 5]) / (1 + negexp_x)
    return prob_x

test_data = np.random.normal(size=[10, 5])
# (sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001
(sigmoid(test_data) - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [ ]:
def softmax_ce(x, label): # 这里label不是一维的
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    "就是计算x与label的交叉熵 -y log x"
    "这个地方有点坑 因为函数外面已经算出来了个 prob 这个prob就是已经 softmax 过的了"
    # loss_array = -np.multiply(np.log(x + 1e-15), label)
    # loss = np.sum(loss_array, axis=-1)
    loss = -np.sum(np.multiply(label, np.log(x + 1e-15)), axis=-1)
    return np.mean(loss)

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data)) - softmax_ce(prob, label))**2 < 0.0001).numpy()
# tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data)), softmax_ce(prob, label)

(<tf.Tensor: shape=(), dtype=float64, numpy=2.567227649862266>,
 1.6815895484753411)

## 实现 sigmoid 交叉熵loss函数

In [ ]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    " 注意这里的 x 还是先 sigmoid 过的 所以 x 是输出的标签"
    x += 1e-15
    loss = - (label * np.log(x) + (1 - label) * np.log(1 - x))
    
    # 返回平均损失
    return np.mean(loss)

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print(test_data, label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()

[ 1.02073432  0.6462654  -0.11012451 -0.11358674  0.27889649 -0.27600711
  0.49358354  0.34211259 -0.67838751 -0.38572479] [1. 1. 0. 0. 1. 0. 1. 1. 0. 0.]


True